### ISSUE TITLE
The right context URI for schema.org

### ISSUE THREAD

**Issue by OmarJAH** [semantifyit/sdo-check#1]
1. Which are acceptable formats for the schema.org context URI? 
2. Which are recommended formats for the schema.org context URI?

The following RegularExpression is used to test acceptable formats:
`/^(https?:\/\/)?(www.)?schema.org\/?$/`
If no acceptable format was found a Critical Error is produced (301, Non-conform @context).

The following RegularExpression is used to test recommended formats:
`/^https?:\/\/schema.org\/$/`
If no recommended format was found a Warning is produced (300, Non-ideal @context).

3. Is this ok? Should we be less strict about recommended formats (especially the missing trailing slash)?

Related links: 
https://lists.w3.org/Archives/Public/public-vocabs/2015Feb/0083.html
https://schema.org/docs/faq.html#19

**Comment by OmarJAH** [comment]
Since on the schema.org website the context URI is given without trailing slash we gonna update the recommended format to 

`/^https?:\/\/schema.org\/?$/`

allowing the trailing slash to be optional

**Comment by Tiggerito** [comment]
You should also escape the dot.  It means any character.

**Comment by OmarJAH** [comment]
So we close this issue with:

The following RegularExpression is used to test acceptable formats:
`/^(https?:\/\/)?(www\.)?schema\.org\/?$/`
If no acceptable format was found a Critical Error is produced (301, Non-conform @context).

The following RegularExpression is used to test recommended formats:
`/^https?:\/\/schema\.org\/?$/`
If no recommended format was found a Warning is produced (300, Non-ideal @context).

So, the recommended variants are:

- http://schema.org
- http://schema.org/
- https://schema.org
- https://schema.org/
